package com.yuncia.wechat.dao;


import java.util.List;

import com.yuncia.wechat.pojo.wap.CustomerOpenid;
import com.yuncia.wechat.pojo.wap.CustomerOpenidExample;
import org.apache.ibatis.annotations.Param;

public interface CustomerOpenidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_openid
     *
     * @mbggenerated
     */
    int countByExample(CustomerOpenidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_openid
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerOpenidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_openid
     *
     * @mbggenerated
     */
    int insert(CustomerOpenid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_openid
     *
     * @mbggenerated
     */
    int insertSelective(CustomerOpenid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_openid
     *
     * @mbggenerated
     */
    List<CustomerOpenid> selectByExample(CustomerOpenidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_openid
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerOpenid record, @Param("example") CustomerOpenidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_openid
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerOpenid record, @Param("example") CustomerOpenidExample example);
    /**
     *
     */
}