package com.yuncia.wechat.pojo.wap;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.education_level_id
     *
     * @mbggenerated
     */
    private Long educationLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.work_state_id
     *
     * @mbggenerated
     */
    private Long workStateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.income_level_id
     *
     * @mbggenerated
     */
    private Long incomeLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.marriage_id
     *
     * @mbggenerated
     */
    private Long marriageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.location_type_id
     *
     * @mbggenerated
     */
    private Long locationTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_account
     *
     * @mbggenerated
     */
    private String customerAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.active_code
     *
     * @mbggenerated
     */
    private String activeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.account_state
     *
     * @mbggenerated
     */
    private Boolean accountState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.first_name
     *
     * @mbggenerated
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.last_name
     *
     * @mbggenerated
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.sex
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.birth_place
     *
     * @mbggenerated
     */
    private String birthPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.birth_date
     *
     * @mbggenerated
     */
    private Date birthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.survey_type
     *
     * @mbggenerated
     */
    private String surveyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone_type
     *
     * @mbggenerated
     */
    private String phoneType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.area_code
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone_num
     *
     * @mbggenerated
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.post_code
     *
     * @mbggenerated
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.card_type
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.card_num
     *
     * @mbggenerated
     */
    private String cardNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.recommender_email
     *
     * @mbggenerated
     */
    private String recommenderEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.recommender_id
     *
     * @mbggenerated
     */
    private String recommenderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.vhobby
     *
     * @mbggenerated
     */
    private Boolean vhobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.vhome
     *
     * @mbggenerated
     */
    private Boolean vhome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.vwork
     *
     * @mbggenerated
     */
    private Boolean vwork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.vcommunication
     *
     * @mbggenerated
     */
    private Boolean vcommunication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.last_modify_date
     *
     * @mbggenerated
     */
    private Date lastModifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.register_ip
     *
     * @mbggenerated
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ip_address
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.credit_cent
     *
     * @mbggenerated
     */
    private Integer creditCent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.current_points
     *
     * @mbggenerated
     */
    private Integer currentPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.total_points
     *
     * @mbggenerated
     */
    private Integer totalPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.manage_state
     *
     * @mbggenerated
     */
    private Boolean manageState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.origin
     *
     * @mbggenerated
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.info_complete
     *
     * @mbggenerated
     */
    private Byte infoComplete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.face
     *
     * @mbggenerated
     */
    private String face;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.is_duiya
     *
     * @mbggenerated
     */
    private Integer isDuiya;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_id
     *
     * @return the value of customer.customer_id
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_id
     *
     * @param customerId the value for customer.customer_id
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.education_level_id
     *
     * @return the value of customer.education_level_id
     * @mbggenerated
     */
    public Long getEducationLevelId() {
        return educationLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.education_level_id
     *
     * @param educationLevelId the value for customer.education_level_id
     * @mbggenerated
     */
    public void setEducationLevelId(Long educationLevelId) {
        this.educationLevelId = educationLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.work_state_id
     *
     * @return the value of customer.work_state_id
     * @mbggenerated
     */
    public Long getWorkStateId() {
        return workStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.work_state_id
     *
     * @param workStateId the value for customer.work_state_id
     * @mbggenerated
     */
    public void setWorkStateId(Long workStateId) {
        this.workStateId = workStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.income_level_id
     *
     * @return the value of customer.income_level_id
     * @mbggenerated
     */
    public Long getIncomeLevelId() {
        return incomeLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.income_level_id
     *
     * @param incomeLevelId the value for customer.income_level_id
     * @mbggenerated
     */
    public void setIncomeLevelId(Long incomeLevelId) {
        this.incomeLevelId = incomeLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.marriage_id
     *
     * @return the value of customer.marriage_id
     * @mbggenerated
     */
    public Long getMarriageId() {
        return marriageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.marriage_id
     *
     * @param marriageId the value for customer.marriage_id
     * @mbggenerated
     */
    public void setMarriageId(Long marriageId) {
        this.marriageId = marriageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.location_type_id
     *
     * @return the value of customer.location_type_id
     * @mbggenerated
     */
    public Long getLocationTypeId() {
        return locationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.location_type_id
     *
     * @param locationTypeId the value for customer.location_type_id
     * @mbggenerated
     */
    public void setLocationTypeId(Long locationTypeId) {
        this.locationTypeId = locationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_account
     *
     * @return the value of customer.customer_account
     * @mbggenerated
     */
    public String getCustomerAccount() {
        return customerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_account
     *
     * @param customerAccount the value for customer.customer_account
     * @mbggenerated
     */
    public void setCustomerAccount(String customerAccount) {
        this.customerAccount = customerAccount == null ? null : customerAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.password
     *
     * @return the value of customer.password
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.password
     *
     * @param password the value for customer.password
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.active_code
     *
     * @return the value of customer.active_code
     * @mbggenerated
     */
    public String getActiveCode() {
        return activeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.active_code
     *
     * @param activeCode the value for customer.active_code
     * @mbggenerated
     */
    public void setActiveCode(String activeCode) {
        this.activeCode = activeCode == null ? null : activeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.account_state
     *
     * @return the value of customer.account_state
     * @mbggenerated
     */
    public Boolean getAccountState() {
        return accountState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.account_state
     *
     * @param accountState the value for customer.account_state
     * @mbggenerated
     */
    public void setAccountState(Boolean accountState) {
        this.accountState = accountState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.first_name
     *
     * @return the value of customer.first_name
     * @mbggenerated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.first_name
     *
     * @param firstName the value for customer.first_name
     * @mbggenerated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.last_name
     *
     * @return the value of customer.last_name
     * @mbggenerated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.last_name
     *
     * @param lastName the value for customer.last_name
     * @mbggenerated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.sex
     *
     * @return the value of customer.sex
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.sex
     *
     * @param sex the value for customer.sex
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.province
     *
     * @return the value of customer.province
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.province
     *
     * @param province the value for customer.province
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.city
     *
     * @return the value of customer.city
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.city
     *
     * @param city the value for customer.city
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.birth_place
     *
     * @return the value of customer.birth_place
     * @mbggenerated
     */
    public String getBirthPlace() {
        return birthPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.birth_place
     *
     * @param birthPlace the value for customer.birth_place
     * @mbggenerated
     */
    public void setBirthPlace(String birthPlace) {
        this.birthPlace = birthPlace == null ? null : birthPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.birth_date
     *
     * @return the value of customer.birth_date
     * @mbggenerated
     */
    public Date getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.birth_date
     *
     * @param birthDate the value for customer.birth_date
     * @mbggenerated
     */
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.email
     *
     * @return the value of customer.email
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.email
     *
     * @param email the value for customer.email
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.survey_type
     *
     * @return the value of customer.survey_type
     * @mbggenerated
     */
    public String getSurveyType() {
        return surveyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.survey_type
     *
     * @param surveyType the value for customer.survey_type
     * @mbggenerated
     */
    public void setSurveyType(String surveyType) {
        this.surveyType = surveyType == null ? null : surveyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.level
     *
     * @return the value of customer.level
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.level
     *
     * @param level the value for customer.level
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone_type
     *
     * @return the value of customer.phone_type
     * @mbggenerated
     */
    public String getPhoneType() {
        return phoneType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone_type
     *
     * @param phoneType the value for customer.phone_type
     * @mbggenerated
     */
    public void setPhoneType(String phoneType) {
        this.phoneType = phoneType == null ? null : phoneType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.area_code
     *
     * @return the value of customer.area_code
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.area_code
     *
     * @param areaCode the value for customer.area_code
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone_num
     *
     * @return the value of customer.phone_num
     * @mbggenerated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone_num
     *
     * @param phoneNum the value for customer.phone_num
     * @mbggenerated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address
     *
     * @return the value of customer.address
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address
     *
     * @param address the value for customer.address
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.post_code
     *
     * @return the value of customer.post_code
     * @mbggenerated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.post_code
     *
     * @param postCode the value for customer.post_code
     * @mbggenerated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.card_type
     *
     * @return the value of customer.card_type
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.card_type
     *
     * @param cardType the value for customer.card_type
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.card_num
     *
     * @return the value of customer.card_num
     * @mbggenerated
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.card_num
     *
     * @param cardNum the value for customer.card_num
     * @mbggenerated
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum == null ? null : cardNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.recommender_email
     *
     * @return the value of customer.recommender_email
     * @mbggenerated
     */
    public String getRecommenderEmail() {
        return recommenderEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.recommender_email
     *
     * @param recommenderEmail the value for customer.recommender_email
     * @mbggenerated
     */
    public void setRecommenderEmail(String recommenderEmail) {
        this.recommenderEmail = recommenderEmail == null ? null : recommenderEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.recommender_id
     *
     * @return the value of customer.recommender_id
     * @mbggenerated
     */
    public String getRecommenderId() {
        return recommenderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.recommender_id
     *
     * @param recommenderId the value for customer.recommender_id
     * @mbggenerated
     */
    public void setRecommenderId(String recommenderId) {
        this.recommenderId = recommenderId == null ? null : recommenderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.vhobby
     *
     * @return the value of customer.vhobby
     * @mbggenerated
     */
    public Boolean getVhobby() {
        return vhobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.vhobby
     *
     * @param vhobby the value for customer.vhobby
     * @mbggenerated
     */
    public void setVhobby(Boolean vhobby) {
        this.vhobby = vhobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.vhome
     *
     * @return the value of customer.vhome
     * @mbggenerated
     */
    public Boolean getVhome() {
        return vhome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.vhome
     *
     * @param vhome the value for customer.vhome
     * @mbggenerated
     */
    public void setVhome(Boolean vhome) {
        this.vhome = vhome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.vwork
     *
     * @return the value of customer.vwork
     * @mbggenerated
     */
    public Boolean getVwork() {
        return vwork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.vwork
     *
     * @param vwork the value for customer.vwork
     * @mbggenerated
     */
    public void setVwork(Boolean vwork) {
        this.vwork = vwork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.vcommunication
     *
     * @return the value of customer.vcommunication
     * @mbggenerated
     */
    public Boolean getVcommunication() {
        return vcommunication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.vcommunication
     *
     * @param vcommunication the value for customer.vcommunication
     * @mbggenerated
     */
    public void setVcommunication(Boolean vcommunication) {
        this.vcommunication = vcommunication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.is_deleted
     *
     * @return the value of customer.is_deleted
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.is_deleted
     *
     * @param isDeleted the value for customer.is_deleted
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.create_date
     *
     * @return the value of customer.create_date
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.create_date
     *
     * @param createDate the value for customer.create_date
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.last_modify_date
     *
     * @return the value of customer.last_modify_date
     * @mbggenerated
     */
    public Date getLastModifyDate() {
        return lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.last_modify_date
     *
     * @param lastModifyDate the value for customer.last_modify_date
     * @mbggenerated
     */
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.register_ip
     *
     * @return the value of customer.register_ip
     * @mbggenerated
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.register_ip
     *
     * @param registerIp the value for customer.register_ip
     * @mbggenerated
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp == null ? null : registerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ip_address
     *
     * @return the value of customer.ip_address
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ip_address
     *
     * @param ipAddress the value for customer.ip_address
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.credit_cent
     *
     * @return the value of customer.credit_cent
     * @mbggenerated
     */
    public Integer getCreditCent() {
        return creditCent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.credit_cent
     *
     * @param creditCent the value for customer.credit_cent
     * @mbggenerated
     */
    public void setCreditCent(Integer creditCent) {
        this.creditCent = creditCent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.current_points
     *
     * @return the value of customer.current_points
     * @mbggenerated
     */
    public Integer getCurrentPoints() {
        return currentPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.current_points
     *
     * @param currentPoints the value for customer.current_points
     * @mbggenerated
     */
    public void setCurrentPoints(Integer currentPoints) {
        this.currentPoints = currentPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.total_points
     *
     * @return the value of customer.total_points
     * @mbggenerated
     */
    public Integer getTotalPoints() {
        return totalPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.total_points
     *
     * @param totalPoints the value for customer.total_points
     * @mbggenerated
     */
    public void setTotalPoints(Integer totalPoints) {
        this.totalPoints = totalPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.manage_state
     *
     * @return the value of customer.manage_state
     * @mbggenerated
     */
    public Boolean getManageState() {
        return manageState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.manage_state
     *
     * @param manageState the value for customer.manage_state
     * @mbggenerated
     */
    public void setManageState(Boolean manageState) {
        this.manageState = manageState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.origin
     *
     * @return the value of customer.origin
     * @mbggenerated
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.origin
     *
     * @param origin the value for customer.origin
     * @mbggenerated
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.info_complete
     *
     * @return the value of customer.info_complete
     * @mbggenerated
     */
    public Byte getInfoComplete() {
        return infoComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.info_complete
     *
     * @param infoComplete the value for customer.info_complete
     * @mbggenerated
     */
    public void setInfoComplete(Byte infoComplete) {
        this.infoComplete = infoComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.face
     *
     * @return the value of customer.face
     * @mbggenerated
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.face
     *
     * @param face the value for customer.face
     * @mbggenerated
     */
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.is_duiya
     *
     * @return the value of customer.is_duiya
     * @mbggenerated
     */
    public Integer getIsDuiya() {
        return isDuiya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.is_duiya
     *
     * @param isDuiya the value for customer.is_duiya
     * @mbggenerated
     */
    public void setIsDuiya(Integer isDuiya) {
        this.isDuiya = isDuiya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.nick_name
     *
     * @return the value of customer.nick_name
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.nick_name
     *
     * @param nickName the value for customer.nick_name
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }
}