package com.yuncia.wechat.pojo.wap;

public class CustomerOpenid {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_openid.customerId
     *
     * @mbggenerated
     */
    private Long customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_openid.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_openid.customerId
     *
     * @return the value of customer_openid.customerId
     * @mbggenerated
     */
    public Long getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_openid.customerId
     *
     * @param customerid the value for customer_openid.customerId
     * @mbggenerated
     */
    public void setCustomerid(Long customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_openid.openid
     *
     * @return the value of customer_openid.openid
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_openid.openid
     *
     * @param openid the value for customer_openid.openid
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }
}