package com.yuncia.wechat.pojo.wap;

public class MzTaxNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mztaxnews.newid
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    private Integer newid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mztaxnews.newtitle
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    private String newtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mztaxnews.newbody
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    private String newbody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mztaxnews.newtime
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    private String newtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mztaxnews.newid
     *
     * @return the value of mztaxnews.newid
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    public Integer getNewid() {
        return newid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mztaxnews.newid
     *
     * @param newid the value for mztaxnews.newid
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    public void setNewid(Integer newid) {
        this.newid = newid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mztaxnews.newtitle
     *
     * @return the value of mztaxnews.newtitle
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    public String getNewtitle() {
        return newtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mztaxnews.newtitle
     *
     * @param newtitle the value for mztaxnews.newtitle
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    public void setNewtitle(String newtitle) {
        this.newtitle = newtitle == null ? null : newtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mztaxnews.newbody
     *
     * @return the value of mztaxnews.newbody
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    public String getNewbody() {
        return newbody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mztaxnews.newbody
     *
     * @param newbody the value for mztaxnews.newbody
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    public void setNewbody(String newbody) {
        this.newbody = newbody == null ? null : newbody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mztaxnews.newtime
     *
     * @return the value of mztaxnews.newtime
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    public String getNewtime() {
        return newtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mztaxnews.newtime
     *
     * @param newtime the value for mztaxnews.newtime
     *
     * @mbggenerated Fri Mar 20 19:52:13 CST 2015
     */
    public void setNewtime(String newtime) {
        this.newtime = newtime == null ? null : newtime.trim();
    }
}