package com.yuncia.wechat.pojo.wap;

import com.yuncia.wechat.util.OtherSystemUtil;
import org.apache.commons.lang.StringUtils;

import java.util.Date;

public class Prize {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.prize_id
     *
     * @mbggenerated
     */
    private Long prizeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.prize_type_id
     *
     * @mbggenerated
     */
    private Long prizeTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.manufacturer
     *
     * @mbggenerated
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.prize_number
     *
     * @mbggenerated
     */
    private String prizeNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.prize_name
     *
     * @mbggenerated
     */
    private String prizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.prize_model
     *
     * @mbggenerated
     */
    private String prizeModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.prize_price
     *
     * @mbggenerated
     */
    private Double prizePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.prize_points
     *
     * @mbggenerated
     */
    private Integer prizePoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.prize_storage
     *
     * @mbggenerated
     */
    private Integer prizeStorage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.prize_click_count
     *
     * @mbggenerated
     */
    private Integer prizeClickCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.prize_sequence
     *
     * @mbggenerated
     */
    private Integer prizeSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.is_showed
     *
     * @mbggenerated
     */
    private Boolean isShowed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.expire_time
     *
     * @mbggenerated
     */
    private Date expireTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.last_modify_time
     *
     * @mbggenerated
     */
    private Date lastModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.last_modifier
     *
     * @mbggenerated
     */
    private String lastModifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.enabled
     *
     * @mbggenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.manufacturer_id
     *
     * @mbggenerated
     */
    private Long manufacturerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.hotline
     *
     * @mbggenerated
     */
    private String hotline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.fare_in_province
     *
     * @mbggenerated
     */
    private Double fareInProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.fare_out_province
     *
     * @mbggenerated
     */
    private Double fareOutProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.record_type
     *
     * @mbggenerated
     */
    private Integer recordType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.image_path
     *
     * @mbggenerated
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.icon_path
     *
     * @mbggenerated
     */
    private String iconPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.version
     *
     * @mbggenerated
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.deleted
     *
     * @mbggenerated
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prize.prize_des
     *
     * @mbggenerated
     */
    private String prizeDes;
    private String showImagePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.prize_id
     *
     * @return the value of prize.prize_id
     * @mbggenerated
     */
    public Long getPrizeId() {
        return prizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.prize_id
     *
     * @param prizeId the value for prize.prize_id
     * @mbggenerated
     */
    public void setPrizeId(Long prizeId) {
        this.prizeId = prizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.prize_type_id
     *
     * @return the value of prize.prize_type_id
     * @mbggenerated
     */
    public Long getPrizeTypeId() {
        return prizeTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.prize_type_id
     *
     * @param prizeTypeId the value for prize.prize_type_id
     * @mbggenerated
     */
    public void setPrizeTypeId(Long prizeTypeId) {
        this.prizeTypeId = prizeTypeId;
    }

    public String getShowImagePath() {
        if(StringUtils.isNotEmpty(iconPath)){
//            showImagePath= OtherSystemUtil.prize_image_url+iconPath;
        }
        return showImagePath;
    }

    public void setShowImagePath(String showImagePath) {
        this.showImagePath = showImagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.manufacturer
     *
     * @return the value of prize.manufacturer
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.manufacturer
     *
     * @param manufacturer the value for prize.manufacturer
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.prize_number
     *
     * @return the value of prize.prize_number
     * @mbggenerated
     */
    public String getPrizeNumber() {
        return prizeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.prize_number
     *
     * @param prizeNumber the value for prize.prize_number
     * @mbggenerated
     */
    public void setPrizeNumber(String prizeNumber) {
        this.prizeNumber = prizeNumber == null ? null : prizeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.prize_name
     *
     * @return the value of prize.prize_name
     * @mbggenerated
     */
    public String getPrizeName() {
        return prizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.prize_name
     *
     * @param prizeName the value for prize.prize_name
     * @mbggenerated
     */
    public void setPrizeName(String prizeName) {
        this.prizeName = prizeName == null ? null : prizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.prize_model
     *
     * @return the value of prize.prize_model
     * @mbggenerated
     */
    public String getPrizeModel() {
        return prizeModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.prize_model
     *
     * @param prizeModel the value for prize.prize_model
     * @mbggenerated
     */
    public void setPrizeModel(String prizeModel) {
        this.prizeModel = prizeModel == null ? null : prizeModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.prize_price
     *
     * @return the value of prize.prize_price
     * @mbggenerated
     */
    public Double getPrizePrice() {
        return prizePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.prize_price
     *
     * @param prizePrice the value for prize.prize_price
     * @mbggenerated
     */
    public void setPrizePrice(Double prizePrice) {
        this.prizePrice = prizePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.prize_points
     *
     * @return the value of prize.prize_points
     * @mbggenerated
     */
    public Integer getPrizePoints() {
        return prizePoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.prize_points
     *
     * @param prizePoints the value for prize.prize_points
     * @mbggenerated
     */
    public void setPrizePoints(Integer prizePoints) {
        this.prizePoints = prizePoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.prize_storage
     *
     * @return the value of prize.prize_storage
     * @mbggenerated
     */
    public Integer getPrizeStorage() {
        return prizeStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.prize_storage
     *
     * @param prizeStorage the value for prize.prize_storage
     * @mbggenerated
     */
    public void setPrizeStorage(Integer prizeStorage) {
        this.prizeStorage = prizeStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.prize_click_count
     *
     * @return the value of prize.prize_click_count
     * @mbggenerated
     */
    public Integer getPrizeClickCount() {
        return prizeClickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.prize_click_count
     *
     * @param prizeClickCount the value for prize.prize_click_count
     * @mbggenerated
     */
    public void setPrizeClickCount(Integer prizeClickCount) {
        this.prizeClickCount = prizeClickCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.prize_sequence
     *
     * @return the value of prize.prize_sequence
     * @mbggenerated
     */
    public Integer getPrizeSequence() {
        return prizeSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.prize_sequence
     *
     * @param prizeSequence the value for prize.prize_sequence
     * @mbggenerated
     */
    public void setPrizeSequence(Integer prizeSequence) {
        this.prizeSequence = prizeSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.is_showed
     *
     * @return the value of prize.is_showed
     * @mbggenerated
     */
    public Boolean getIsShowed() {
        return isShowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.is_showed
     *
     * @param isShowed the value for prize.is_showed
     * @mbggenerated
     */
    public void setIsShowed(Boolean isShowed) {
        this.isShowed = isShowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.expire_time
     *
     * @return the value of prize.expire_time
     * @mbggenerated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.expire_time
     *
     * @param expireTime the value for prize.expire_time
     * @mbggenerated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.create_time
     *
     * @return the value of prize.create_time
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.create_time
     *
     * @param createTime the value for prize.create_time
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.creator
     *
     * @return the value of prize.creator
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.creator
     *
     * @param creator the value for prize.creator
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.last_modify_time
     *
     * @return the value of prize.last_modify_time
     * @mbggenerated
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.last_modify_time
     *
     * @param lastModifyTime the value for prize.last_modify_time
     * @mbggenerated
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.last_modifier
     *
     * @return the value of prize.last_modifier
     * @mbggenerated
     */
    public String getLastModifier() {
        return lastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.last_modifier
     *
     * @param lastModifier the value for prize.last_modifier
     * @mbggenerated
     */
    public void setLastModifier(String lastModifier) {
        this.lastModifier = lastModifier == null ? null : lastModifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.enabled
     *
     * @return the value of prize.enabled
     * @mbggenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.enabled
     *
     * @param enabled the value for prize.enabled
     * @mbggenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.manufacturer_id
     *
     * @return the value of prize.manufacturer_id
     * @mbggenerated
     */
    public Long getManufacturerId() {
        return manufacturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.manufacturer_id
     *
     * @param manufacturerId the value for prize.manufacturer_id
     * @mbggenerated
     */
    public void setManufacturerId(Long manufacturerId) {
        this.manufacturerId = manufacturerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.hotline
     *
     * @return the value of prize.hotline
     * @mbggenerated
     */
    public String getHotline() {
        return hotline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.hotline
     *
     * @param hotline the value for prize.hotline
     * @mbggenerated
     */
    public void setHotline(String hotline) {
        this.hotline = hotline == null ? null : hotline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.fare_in_province
     *
     * @return the value of prize.fare_in_province
     * @mbggenerated
     */
    public Double getFareInProvince() {
        return fareInProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.fare_in_province
     *
     * @param fareInProvince the value for prize.fare_in_province
     * @mbggenerated
     */
    public void setFareInProvince(Double fareInProvince) {
        this.fareInProvince = fareInProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.fare_out_province
     *
     * @return the value of prize.fare_out_province
     * @mbggenerated
     */
    public Double getFareOutProvince() {
        return fareOutProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.fare_out_province
     *
     * @param fareOutProvince the value for prize.fare_out_province
     * @mbggenerated
     */
    public void setFareOutProvince(Double fareOutProvince) {
        this.fareOutProvince = fareOutProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.status
     *
     * @return the value of prize.status
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.status
     *
     * @param status the value for prize.status
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.remark
     *
     * @return the value of prize.remark
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.remark
     *
     * @param remark the value for prize.remark
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.record_type
     *
     * @return the value of prize.record_type
     * @mbggenerated
     */
    public Integer getRecordType() {
        return recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.record_type
     *
     * @param recordType the value for prize.record_type
     * @mbggenerated
     */
    public void setRecordType(Integer recordType) {
        this.recordType = recordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.image_path
     *
     * @return the value of prize.image_path
     * @mbggenerated
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.image_path
     *
     * @param imagePath the value for prize.image_path
     * @mbggenerated
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.icon_path
     *
     * @return the value of prize.icon_path
     * @mbggenerated
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.icon_path
     *
     * @param iconPath the value for prize.icon_path
     * @mbggenerated
     */
    public void setIconPath(String iconPath) {
        this.iconPath = iconPath == null ? null : iconPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.version
     *
     * @return the value of prize.version
     * @mbggenerated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.version
     *
     * @param version the value for prize.version
     * @mbggenerated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.deleted
     *
     * @return the value of prize.deleted
     * @mbggenerated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.deleted
     *
     * @param deleted the value for prize.deleted
     * @mbggenerated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prize.prize_des
     *
     * @return the value of prize.prize_des
     * @mbggenerated
     */
    public String getPrizeDes() {
        return prizeDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prize.prize_des
     *
     * @param prizeDes the value for prize.prize_des
     * @mbggenerated
     */
    public void setPrizeDes(String prizeDes) {
        this.prizeDes = prizeDes == null ? null : prizeDes.trim();
    }
}