package com.yuncia.wechat.pojo.wap;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PrizeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prize
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prize
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prize
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prize
     *
     * @mbggenerated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prize
     *
     * @mbggenerated
     */
    protected int limit = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public PrizeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart = limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public void setLimit(int limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prize
     *
     * @mbggenerated
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table prize
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPrizeIdIsNull() {
            addCriterion("prize_id is null");
            return (Criteria) this;
        }

        public Criteria andPrizeIdIsNotNull() {
            addCriterion("prize_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeIdEqualTo(Long value) {
            addCriterion("prize_id =", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotEqualTo(Long value) {
            addCriterion("prize_id <>", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdGreaterThan(Long value) {
            addCriterion("prize_id >", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("prize_id >=", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdLessThan(Long value) {
            addCriterion("prize_id <", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdLessThanOrEqualTo(Long value) {
            addCriterion("prize_id <=", value, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdIn(List<Long> values) {
            addCriterion("prize_id in", values, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotIn(List<Long> values) {
            addCriterion("prize_id not in", values, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdBetween(Long value1, Long value2) {
            addCriterion("prize_id between", value1, value2, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeIdNotBetween(Long value1, Long value2) {
            addCriterion("prize_id not between", value1, value2, "prizeId");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdIsNull() {
            addCriterion("prize_type_id is null");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdIsNotNull() {
            addCriterion("prize_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdEqualTo(Long value) {
            addCriterion("prize_type_id =", value, "prizeTypeId");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdNotEqualTo(Long value) {
            addCriterion("prize_type_id <>", value, "prizeTypeId");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdGreaterThan(Long value) {
            addCriterion("prize_type_id >", value, "prizeTypeId");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("prize_type_id >=", value, "prizeTypeId");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdLessThan(Long value) {
            addCriterion("prize_type_id <", value, "prizeTypeId");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("prize_type_id <=", value, "prizeTypeId");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdIn(List<Long> values) {
            addCriterion("prize_type_id in", values, "prizeTypeId");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdNotIn(List<Long> values) {
            addCriterion("prize_type_id not in", values, "prizeTypeId");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdBetween(Long value1, Long value2) {
            addCriterion("prize_type_id between", value1, value2, "prizeTypeId");
            return (Criteria) this;
        }

        public Criteria andPrizeTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("prize_type_id not between", value1, value2, "prizeTypeId");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNull() {
            addCriterion("manufacturer is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerIsNotNull() {
            addCriterion("manufacturer is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerEqualTo(String value) {
            addCriterion("manufacturer =", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotEqualTo(String value) {
            addCriterion("manufacturer <>", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThan(String value) {
            addCriterion("manufacturer >", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerGreaterThanOrEqualTo(String value) {
            addCriterion("manufacturer >=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThan(String value) {
            addCriterion("manufacturer <", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLessThanOrEqualTo(String value) {
            addCriterion("manufacturer <=", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerLike(String value) {
            addCriterion("manufacturer like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotLike(String value) {
            addCriterion("manufacturer not like", value, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerIn(List<String> values) {
            addCriterion("manufacturer in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotIn(List<String> values) {
            addCriterion("manufacturer not in", values, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerBetween(String value1, String value2) {
            addCriterion("manufacturer between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andManufacturerNotBetween(String value1, String value2) {
            addCriterion("manufacturer not between", value1, value2, "manufacturer");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberIsNull() {
            addCriterion("prize_number is null");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberIsNotNull() {
            addCriterion("prize_number is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberEqualTo(String value) {
            addCriterion("prize_number =", value, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberNotEqualTo(String value) {
            addCriterion("prize_number <>", value, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberGreaterThan(String value) {
            addCriterion("prize_number >", value, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberGreaterThanOrEqualTo(String value) {
            addCriterion("prize_number >=", value, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberLessThan(String value) {
            addCriterion("prize_number <", value, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberLessThanOrEqualTo(String value) {
            addCriterion("prize_number <=", value, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberLike(String value) {
            addCriterion("prize_number like", value, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberNotLike(String value) {
            addCriterion("prize_number not like", value, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberIn(List<String> values) {
            addCriterion("prize_number in", values, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberNotIn(List<String> values) {
            addCriterion("prize_number not in", values, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberBetween(String value1, String value2) {
            addCriterion("prize_number between", value1, value2, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNumberNotBetween(String value1, String value2) {
            addCriterion("prize_number not between", value1, value2, "prizeNumber");
            return (Criteria) this;
        }

        public Criteria andPrizeNameIsNull() {
            addCriterion("prize_name is null");
            return (Criteria) this;
        }

        public Criteria andPrizeNameIsNotNull() {
            addCriterion("prize_name is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeNameEqualTo(String value) {
            addCriterion("prize_name =", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotEqualTo(String value) {
            addCriterion("prize_name <>", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameGreaterThan(String value) {
            addCriterion("prize_name >", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameGreaterThanOrEqualTo(String value) {
            addCriterion("prize_name >=", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameLessThan(String value) {
            addCriterion("prize_name <", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameLessThanOrEqualTo(String value) {
            addCriterion("prize_name <=", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameLike(String value) {
            addCriterion("prize_name like", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotLike(String value) {
            addCriterion("prize_name not like", value, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameIn(List<String> values) {
            addCriterion("prize_name in", values, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotIn(List<String> values) {
            addCriterion("prize_name not in", values, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameBetween(String value1, String value2) {
            addCriterion("prize_name between", value1, value2, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeNameNotBetween(String value1, String value2) {
            addCriterion("prize_name not between", value1, value2, "prizeName");
            return (Criteria) this;
        }

        public Criteria andPrizeModelIsNull() {
            addCriterion("prize_model is null");
            return (Criteria) this;
        }

        public Criteria andPrizeModelIsNotNull() {
            addCriterion("prize_model is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeModelEqualTo(String value) {
            addCriterion("prize_model =", value, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizeModelNotEqualTo(String value) {
            addCriterion("prize_model <>", value, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizeModelGreaterThan(String value) {
            addCriterion("prize_model >", value, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizeModelGreaterThanOrEqualTo(String value) {
            addCriterion("prize_model >=", value, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizeModelLessThan(String value) {
            addCriterion("prize_model <", value, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizeModelLessThanOrEqualTo(String value) {
            addCriterion("prize_model <=", value, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizeModelLike(String value) {
            addCriterion("prize_model like", value, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizeModelNotLike(String value) {
            addCriterion("prize_model not like", value, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizeModelIn(List<String> values) {
            addCriterion("prize_model in", values, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizeModelNotIn(List<String> values) {
            addCriterion("prize_model not in", values, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizeModelBetween(String value1, String value2) {
            addCriterion("prize_model between", value1, value2, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizeModelNotBetween(String value1, String value2) {
            addCriterion("prize_model not between", value1, value2, "prizeModel");
            return (Criteria) this;
        }

        public Criteria andPrizePriceIsNull() {
            addCriterion("prize_price is null");
            return (Criteria) this;
        }

        public Criteria andPrizePriceIsNotNull() {
            addCriterion("prize_price is not null");
            return (Criteria) this;
        }

        public Criteria andPrizePriceEqualTo(Double value) {
            addCriterion("prize_price =", value, "prizePrice");
            return (Criteria) this;
        }

        public Criteria andPrizePriceNotEqualTo(Double value) {
            addCriterion("prize_price <>", value, "prizePrice");
            return (Criteria) this;
        }

        public Criteria andPrizePriceGreaterThan(Double value) {
            addCriterion("prize_price >", value, "prizePrice");
            return (Criteria) this;
        }

        public Criteria andPrizePriceGreaterThanOrEqualTo(Double value) {
            addCriterion("prize_price >=", value, "prizePrice");
            return (Criteria) this;
        }

        public Criteria andPrizePriceLessThan(Double value) {
            addCriterion("prize_price <", value, "prizePrice");
            return (Criteria) this;
        }

        public Criteria andPrizePriceLessThanOrEqualTo(Double value) {
            addCriterion("prize_price <=", value, "prizePrice");
            return (Criteria) this;
        }

        public Criteria andPrizePriceIn(List<Double> values) {
            addCriterion("prize_price in", values, "prizePrice");
            return (Criteria) this;
        }

        public Criteria andPrizePriceNotIn(List<Double> values) {
            addCriterion("prize_price not in", values, "prizePrice");
            return (Criteria) this;
        }

        public Criteria andPrizePriceBetween(Double value1, Double value2) {
            addCriterion("prize_price between", value1, value2, "prizePrice");
            return (Criteria) this;
        }

        public Criteria andPrizePriceNotBetween(Double value1, Double value2) {
            addCriterion("prize_price not between", value1, value2, "prizePrice");
            return (Criteria) this;
        }

        public Criteria andPrizePointsIsNull() {
            addCriterion("prize_points is null");
            return (Criteria) this;
        }

        public Criteria andPrizePointsIsNotNull() {
            addCriterion("prize_points is not null");
            return (Criteria) this;
        }

        public Criteria andPrizePointsEqualTo(Integer value) {
            addCriterion("prize_points =", value, "prizePoints");
            return (Criteria) this;
        }

        public Criteria andPrizePointsNotEqualTo(Integer value) {
            addCriterion("prize_points <>", value, "prizePoints");
            return (Criteria) this;
        }

        public Criteria andPrizePointsGreaterThan(Integer value) {
            addCriterion("prize_points >", value, "prizePoints");
            return (Criteria) this;
        }

        public Criteria andPrizePointsGreaterThanOrEqualTo(Integer value) {
            addCriterion("prize_points >=", value, "prizePoints");
            return (Criteria) this;
        }

        public Criteria andPrizePointsLessThan(Integer value) {
            addCriterion("prize_points <", value, "prizePoints");
            return (Criteria) this;
        }

        public Criteria andPrizePointsLessThanOrEqualTo(Integer value) {
            addCriterion("prize_points <=", value, "prizePoints");
            return (Criteria) this;
        }

        public Criteria andPrizePointsIn(List<Integer> values) {
            addCriterion("prize_points in", values, "prizePoints");
            return (Criteria) this;
        }

        public Criteria andPrizePointsNotIn(List<Integer> values) {
            addCriterion("prize_points not in", values, "prizePoints");
            return (Criteria) this;
        }

        public Criteria andPrizePointsBetween(Integer value1, Integer value2) {
            addCriterion("prize_points between", value1, value2, "prizePoints");
            return (Criteria) this;
        }

        public Criteria andPrizePointsNotBetween(Integer value1, Integer value2) {
            addCriterion("prize_points not between", value1, value2, "prizePoints");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageIsNull() {
            addCriterion("prize_storage is null");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageIsNotNull() {
            addCriterion("prize_storage is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageEqualTo(Integer value) {
            addCriterion("prize_storage =", value, "prizeStorage");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageNotEqualTo(Integer value) {
            addCriterion("prize_storage <>", value, "prizeStorage");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageGreaterThan(Integer value) {
            addCriterion("prize_storage >", value, "prizeStorage");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageGreaterThanOrEqualTo(Integer value) {
            addCriterion("prize_storage >=", value, "prizeStorage");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageLessThan(Integer value) {
            addCriterion("prize_storage <", value, "prizeStorage");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageLessThanOrEqualTo(Integer value) {
            addCriterion("prize_storage <=", value, "prizeStorage");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageIn(List<Integer> values) {
            addCriterion("prize_storage in", values, "prizeStorage");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageNotIn(List<Integer> values) {
            addCriterion("prize_storage not in", values, "prizeStorage");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageBetween(Integer value1, Integer value2) {
            addCriterion("prize_storage between", value1, value2, "prizeStorage");
            return (Criteria) this;
        }

        public Criteria andPrizeStorageNotBetween(Integer value1, Integer value2) {
            addCriterion("prize_storage not between", value1, value2, "prizeStorage");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountIsNull() {
            addCriterion("prize_click_count is null");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountIsNotNull() {
            addCriterion("prize_click_count is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountEqualTo(Integer value) {
            addCriterion("prize_click_count =", value, "prizeClickCount");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountNotEqualTo(Integer value) {
            addCriterion("prize_click_count <>", value, "prizeClickCount");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountGreaterThan(Integer value) {
            addCriterion("prize_click_count >", value, "prizeClickCount");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("prize_click_count >=", value, "prizeClickCount");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountLessThan(Integer value) {
            addCriterion("prize_click_count <", value, "prizeClickCount");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountLessThanOrEqualTo(Integer value) {
            addCriterion("prize_click_count <=", value, "prizeClickCount");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountIn(List<Integer> values) {
            addCriterion("prize_click_count in", values, "prizeClickCount");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountNotIn(List<Integer> values) {
            addCriterion("prize_click_count not in", values, "prizeClickCount");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountBetween(Integer value1, Integer value2) {
            addCriterion("prize_click_count between", value1, value2, "prizeClickCount");
            return (Criteria) this;
        }

        public Criteria andPrizeClickCountNotBetween(Integer value1, Integer value2) {
            addCriterion("prize_click_count not between", value1, value2, "prizeClickCount");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceIsNull() {
            addCriterion("prize_sequence is null");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceIsNotNull() {
            addCriterion("prize_sequence is not null");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceEqualTo(Integer value) {
            addCriterion("prize_sequence =", value, "prizeSequence");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceNotEqualTo(Integer value) {
            addCriterion("prize_sequence <>", value, "prizeSequence");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceGreaterThan(Integer value) {
            addCriterion("prize_sequence >", value, "prizeSequence");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceGreaterThanOrEqualTo(Integer value) {
            addCriterion("prize_sequence >=", value, "prizeSequence");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceLessThan(Integer value) {
            addCriterion("prize_sequence <", value, "prizeSequence");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceLessThanOrEqualTo(Integer value) {
            addCriterion("prize_sequence <=", value, "prizeSequence");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceIn(List<Integer> values) {
            addCriterion("prize_sequence in", values, "prizeSequence");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceNotIn(List<Integer> values) {
            addCriterion("prize_sequence not in", values, "prizeSequence");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceBetween(Integer value1, Integer value2) {
            addCriterion("prize_sequence between", value1, value2, "prizeSequence");
            return (Criteria) this;
        }

        public Criteria andPrizeSequenceNotBetween(Integer value1, Integer value2) {
            addCriterion("prize_sequence not between", value1, value2, "prizeSequence");
            return (Criteria) this;
        }

        public Criteria andIsShowedIsNull() {
            addCriterion("is_showed is null");
            return (Criteria) this;
        }

        public Criteria andIsShowedIsNotNull() {
            addCriterion("is_showed is not null");
            return (Criteria) this;
        }

        public Criteria andIsShowedEqualTo(Boolean value) {
            addCriterion("is_showed =", value, "isShowed");
            return (Criteria) this;
        }

        public Criteria andIsShowedNotEqualTo(Boolean value) {
            addCriterion("is_showed <>", value, "isShowed");
            return (Criteria) this;
        }

        public Criteria andIsShowedGreaterThan(Boolean value) {
            addCriterion("is_showed >", value, "isShowed");
            return (Criteria) this;
        }

        public Criteria andIsShowedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_showed >=", value, "isShowed");
            return (Criteria) this;
        }

        public Criteria andIsShowedLessThan(Boolean value) {
            addCriterion("is_showed <", value, "isShowed");
            return (Criteria) this;
        }

        public Criteria andIsShowedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_showed <=", value, "isShowed");
            return (Criteria) this;
        }

        public Criteria andIsShowedIn(List<Boolean> values) {
            addCriterion("is_showed in", values, "isShowed");
            return (Criteria) this;
        }

        public Criteria andIsShowedNotIn(List<Boolean> values) {
            addCriterion("is_showed not in", values, "isShowed");
            return (Criteria) this;
        }

        public Criteria andIsShowedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_showed between", value1, value2, "isShowed");
            return (Criteria) this;
        }

        public Criteria andIsShowedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_showed not between", value1, value2, "isShowed");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIsNull() {
            addCriterion("expire_time is null");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIsNotNull() {
            addCriterion("expire_time is not null");
            return (Criteria) this;
        }

        public Criteria andExpireTimeEqualTo(Date value) {
            addCriterion("expire_time =", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotEqualTo(Date value) {
            addCriterion("expire_time <>", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeGreaterThan(Date value) {
            addCriterion("expire_time >", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("expire_time >=", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeLessThan(Date value) {
            addCriterion("expire_time <", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeLessThanOrEqualTo(Date value) {
            addCriterion("expire_time <=", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIn(List<Date> values) {
            addCriterion("expire_time in", values, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotIn(List<Date> values) {
            addCriterion("expire_time not in", values, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeBetween(Date value1, Date value2) {
            addCriterion("expire_time between", value1, value2, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotBetween(Date value1, Date value2) {
            addCriterion("expire_time not between", value1, value2, "expireTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNull() {
            addCriterion("last_modify_time is null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIsNotNull() {
            addCriterion("last_modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeEqualTo(Date value) {
            addCriterion("last_modify_time =", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotEqualTo(Date value) {
            addCriterion("last_modify_time <>", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThan(Date value) {
            addCriterion("last_modify_time >", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_modify_time >=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThan(Date value) {
            addCriterion("last_modify_time <", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_modify_time <=", value, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeIn(List<Date> values) {
            addCriterion("last_modify_time in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotIn(List<Date> values) {
            addCriterion("last_modify_time not in", values, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeBetween(Date value1, Date value2) {
            addCriterion("last_modify_time between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_modify_time not between", value1, value2, "lastModifyTime");
            return (Criteria) this;
        }

        public Criteria andLastModifierIsNull() {
            addCriterion("last_modifier is null");
            return (Criteria) this;
        }

        public Criteria andLastModifierIsNotNull() {
            addCriterion("last_modifier is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifierEqualTo(String value) {
            addCriterion("last_modifier =", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotEqualTo(String value) {
            addCriterion("last_modifier <>", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierGreaterThan(String value) {
            addCriterion("last_modifier >", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierGreaterThanOrEqualTo(String value) {
            addCriterion("last_modifier >=", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierLessThan(String value) {
            addCriterion("last_modifier <", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierLessThanOrEqualTo(String value) {
            addCriterion("last_modifier <=", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierLike(String value) {
            addCriterion("last_modifier like", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotLike(String value) {
            addCriterion("last_modifier not like", value, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierIn(List<String> values) {
            addCriterion("last_modifier in", values, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotIn(List<String> values) {
            addCriterion("last_modifier not in", values, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierBetween(String value1, String value2) {
            addCriterion("last_modifier between", value1, value2, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andLastModifierNotBetween(String value1, String value2) {
            addCriterion("last_modifier not between", value1, value2, "lastModifier");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNull() {
            addCriterion("enabled is null");
            return (Criteria) this;
        }

        public Criteria andEnabledIsNotNull() {
            addCriterion("enabled is not null");
            return (Criteria) this;
        }

        public Criteria andEnabledEqualTo(Boolean value) {
            addCriterion("enabled =", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotEqualTo(Boolean value) {
            addCriterion("enabled <>", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThan(Boolean value) {
            addCriterion("enabled >", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enabled >=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThan(Boolean value) {
            addCriterion("enabled <", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledLessThanOrEqualTo(Boolean value) {
            addCriterion("enabled <=", value, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledIn(List<Boolean> values) {
            addCriterion("enabled in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotIn(List<Boolean> values) {
            addCriterion("enabled not in", values, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andEnabledNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enabled not between", value1, value2, "enabled");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdIsNull() {
            addCriterion("manufacturer_id is null");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdIsNotNull() {
            addCriterion("manufacturer_id is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdEqualTo(Long value) {
            addCriterion("manufacturer_id =", value, "manufacturerId");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdNotEqualTo(Long value) {
            addCriterion("manufacturer_id <>", value, "manufacturerId");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdGreaterThan(Long value) {
            addCriterion("manufacturer_id >", value, "manufacturerId");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("manufacturer_id >=", value, "manufacturerId");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdLessThan(Long value) {
            addCriterion("manufacturer_id <", value, "manufacturerId");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdLessThanOrEqualTo(Long value) {
            addCriterion("manufacturer_id <=", value, "manufacturerId");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdIn(List<Long> values) {
            addCriterion("manufacturer_id in", values, "manufacturerId");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdNotIn(List<Long> values) {
            addCriterion("manufacturer_id not in", values, "manufacturerId");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdBetween(Long value1, Long value2) {
            addCriterion("manufacturer_id between", value1, value2, "manufacturerId");
            return (Criteria) this;
        }

        public Criteria andManufacturerIdNotBetween(Long value1, Long value2) {
            addCriterion("manufacturer_id not between", value1, value2, "manufacturerId");
            return (Criteria) this;
        }

        public Criteria andHotlineIsNull() {
            addCriterion("hotline is null");
            return (Criteria) this;
        }

        public Criteria andHotlineIsNotNull() {
            addCriterion("hotline is not null");
            return (Criteria) this;
        }

        public Criteria andHotlineEqualTo(String value) {
            addCriterion("hotline =", value, "hotline");
            return (Criteria) this;
        }

        public Criteria andHotlineNotEqualTo(String value) {
            addCriterion("hotline <>", value, "hotline");
            return (Criteria) this;
        }

        public Criteria andHotlineGreaterThan(String value) {
            addCriterion("hotline >", value, "hotline");
            return (Criteria) this;
        }

        public Criteria andHotlineGreaterThanOrEqualTo(String value) {
            addCriterion("hotline >=", value, "hotline");
            return (Criteria) this;
        }

        public Criteria andHotlineLessThan(String value) {
            addCriterion("hotline <", value, "hotline");
            return (Criteria) this;
        }

        public Criteria andHotlineLessThanOrEqualTo(String value) {
            addCriterion("hotline <=", value, "hotline");
            return (Criteria) this;
        }

        public Criteria andHotlineLike(String value) {
            addCriterion("hotline like", value, "hotline");
            return (Criteria) this;
        }

        public Criteria andHotlineNotLike(String value) {
            addCriterion("hotline not like", value, "hotline");
            return (Criteria) this;
        }

        public Criteria andHotlineIn(List<String> values) {
            addCriterion("hotline in", values, "hotline");
            return (Criteria) this;
        }

        public Criteria andHotlineNotIn(List<String> values) {
            addCriterion("hotline not in", values, "hotline");
            return (Criteria) this;
        }

        public Criteria andHotlineBetween(String value1, String value2) {
            addCriterion("hotline between", value1, value2, "hotline");
            return (Criteria) this;
        }

        public Criteria andHotlineNotBetween(String value1, String value2) {
            addCriterion("hotline not between", value1, value2, "hotline");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceIsNull() {
            addCriterion("fare_in_province is null");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceIsNotNull() {
            addCriterion("fare_in_province is not null");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceEqualTo(Double value) {
            addCriterion("fare_in_province =", value, "fareInProvince");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceNotEqualTo(Double value) {
            addCriterion("fare_in_province <>", value, "fareInProvince");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceGreaterThan(Double value) {
            addCriterion("fare_in_province >", value, "fareInProvince");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceGreaterThanOrEqualTo(Double value) {
            addCriterion("fare_in_province >=", value, "fareInProvince");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceLessThan(Double value) {
            addCriterion("fare_in_province <", value, "fareInProvince");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceLessThanOrEqualTo(Double value) {
            addCriterion("fare_in_province <=", value, "fareInProvince");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceIn(List<Double> values) {
            addCriterion("fare_in_province in", values, "fareInProvince");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceNotIn(List<Double> values) {
            addCriterion("fare_in_province not in", values, "fareInProvince");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceBetween(Double value1, Double value2) {
            addCriterion("fare_in_province between", value1, value2, "fareInProvince");
            return (Criteria) this;
        }

        public Criteria andFareInProvinceNotBetween(Double value1, Double value2) {
            addCriterion("fare_in_province not between", value1, value2, "fareInProvince");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceIsNull() {
            addCriterion("fare_out_province is null");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceIsNotNull() {
            addCriterion("fare_out_province is not null");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceEqualTo(Double value) {
            addCriterion("fare_out_province =", value, "fareOutProvince");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceNotEqualTo(Double value) {
            addCriterion("fare_out_province <>", value, "fareOutProvince");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceGreaterThan(Double value) {
            addCriterion("fare_out_province >", value, "fareOutProvince");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceGreaterThanOrEqualTo(Double value) {
            addCriterion("fare_out_province >=", value, "fareOutProvince");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceLessThan(Double value) {
            addCriterion("fare_out_province <", value, "fareOutProvince");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceLessThanOrEqualTo(Double value) {
            addCriterion("fare_out_province <=", value, "fareOutProvince");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceIn(List<Double> values) {
            addCriterion("fare_out_province in", values, "fareOutProvince");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceNotIn(List<Double> values) {
            addCriterion("fare_out_province not in", values, "fareOutProvince");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceBetween(Double value1, Double value2) {
            addCriterion("fare_out_province between", value1, value2, "fareOutProvince");
            return (Criteria) this;
        }

        public Criteria andFareOutProvinceNotBetween(Double value1, Double value2) {
            addCriterion("fare_out_province not between", value1, value2, "fareOutProvince");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIsNull() {
            addCriterion("record_type is null");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIsNotNull() {
            addCriterion("record_type is not null");
            return (Criteria) this;
        }

        public Criteria andRecordTypeEqualTo(Integer value) {
            addCriterion("record_type =", value, "recordType");
            return (Criteria) this;
        }

        public Criteria andRecordTypeNotEqualTo(Integer value) {
            addCriterion("record_type <>", value, "recordType");
            return (Criteria) this;
        }

        public Criteria andRecordTypeGreaterThan(Integer value) {
            addCriterion("record_type >", value, "recordType");
            return (Criteria) this;
        }

        public Criteria andRecordTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("record_type >=", value, "recordType");
            return (Criteria) this;
        }

        public Criteria andRecordTypeLessThan(Integer value) {
            addCriterion("record_type <", value, "recordType");
            return (Criteria) this;
        }

        public Criteria andRecordTypeLessThanOrEqualTo(Integer value) {
            addCriterion("record_type <=", value, "recordType");
            return (Criteria) this;
        }

        public Criteria andRecordTypeIn(List<Integer> values) {
            addCriterion("record_type in", values, "recordType");
            return (Criteria) this;
        }

        public Criteria andRecordTypeNotIn(List<Integer> values) {
            addCriterion("record_type not in", values, "recordType");
            return (Criteria) this;
        }

        public Criteria andRecordTypeBetween(Integer value1, Integer value2) {
            addCriterion("record_type between", value1, value2, "recordType");
            return (Criteria) this;
        }

        public Criteria andRecordTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("record_type not between", value1, value2, "recordType");
            return (Criteria) this;
        }

        public Criteria andImagePathIsNull() {
            addCriterion("image_path is null");
            return (Criteria) this;
        }

        public Criteria andImagePathIsNotNull() {
            addCriterion("image_path is not null");
            return (Criteria) this;
        }

        public Criteria andImagePathEqualTo(String value) {
            addCriterion("image_path =", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotEqualTo(String value) {
            addCriterion("image_path <>", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathGreaterThan(String value) {
            addCriterion("image_path >", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathGreaterThanOrEqualTo(String value) {
            addCriterion("image_path >=", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLessThan(String value) {
            addCriterion("image_path <", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLessThanOrEqualTo(String value) {
            addCriterion("image_path <=", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathLike(String value) {
            addCriterion("image_path like", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotLike(String value) {
            addCriterion("image_path not like", value, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathIn(List<String> values) {
            addCriterion("image_path in", values, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotIn(List<String> values) {
            addCriterion("image_path not in", values, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathBetween(String value1, String value2) {
            addCriterion("image_path between", value1, value2, "imagePath");
            return (Criteria) this;
        }

        public Criteria andImagePathNotBetween(String value1, String value2) {
            addCriterion("image_path not between", value1, value2, "imagePath");
            return (Criteria) this;
        }

        public Criteria andIconPathIsNull() {
            addCriterion("icon_path is null");
            return (Criteria) this;
        }

        public Criteria andIconPathIsNotNull() {
            addCriterion("icon_path is not null");
            return (Criteria) this;
        }

        public Criteria andIconPathEqualTo(String value) {
            addCriterion("icon_path =", value, "iconPath");
            return (Criteria) this;
        }

        public Criteria andIconPathNotEqualTo(String value) {
            addCriterion("icon_path <>", value, "iconPath");
            return (Criteria) this;
        }

        public Criteria andIconPathGreaterThan(String value) {
            addCriterion("icon_path >", value, "iconPath");
            return (Criteria) this;
        }

        public Criteria andIconPathGreaterThanOrEqualTo(String value) {
            addCriterion("icon_path >=", value, "iconPath");
            return (Criteria) this;
        }

        public Criteria andIconPathLessThan(String value) {
            addCriterion("icon_path <", value, "iconPath");
            return (Criteria) this;
        }

        public Criteria andIconPathLessThanOrEqualTo(String value) {
            addCriterion("icon_path <=", value, "iconPath");
            return (Criteria) this;
        }

        public Criteria andIconPathLike(String value) {
            addCriterion("icon_path like", value, "iconPath");
            return (Criteria) this;
        }

        public Criteria andIconPathNotLike(String value) {
            addCriterion("icon_path not like", value, "iconPath");
            return (Criteria) this;
        }

        public Criteria andIconPathIn(List<String> values) {
            addCriterion("icon_path in", values, "iconPath");
            return (Criteria) this;
        }

        public Criteria andIconPathNotIn(List<String> values) {
            addCriterion("icon_path not in", values, "iconPath");
            return (Criteria) this;
        }

        public Criteria andIconPathBetween(String value1, String value2) {
            addCriterion("icon_path between", value1, value2, "iconPath");
            return (Criteria) this;
        }

        public Criteria andIconPathNotBetween(String value1, String value2) {
            addCriterion("icon_path not between", value1, value2, "iconPath");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Boolean value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Boolean value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Boolean value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Boolean value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Boolean> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Boolean> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table prize
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table prize
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}